# Generated by Django 2.2.24 on 2021-08-22 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name_plural': 'toppings'},
        ),
        migrations.AlterField(
            model_name='topping',
            name='pizza_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='pizzas.Pizza'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='topping',
            field=models.CharField(max_length=200),
        ),
    ]
